### ISSUE TITLE
Can this package be used for retrieving chunks of a file?

### ISSUE THREAD

**Issue by janko** [goto-bus-stop/from2-blob#1]
Hello 👋

I'm trying to figure the simplest way to calculate and MD5 hash of a file. I would like to use [`js-spark-md5`](https://github.com/satazor/js-spark-md5#hash-a-file-incrementally), which supports incremental hashing, and it shows an [example](https://github.com/satazor/js-spark-md5#hash-a-file-incrementally) of how to incrementally calculate an MD5 hash of a file by reading it in chunks.

I could just copy-paste that example, but I'm searching for a package that handles reading a file in chunks, as that's the most complex thing for me in that example. Can perhaps this package help me in that regard?

**Comment by goto-bus-stop** [comment]
You can do something like this:

```js
var fromBlob = require('from2-blob')
fromBlob(new Blob([ ... ])).on('data', function (buffer) {
  // may have to convert `buffer` to an ArrayBuffer
  // it's a Uint8Array here
  spark.append(buffer)
})
```

Note that from2-blob uses Node streams so it returns Node-style Buffers (based on Uint8Arrays) rather than ArrayBuffers. It's mostly intended for use together with existing node streams modules. The Node stream + buffer stuff takes a bunch of KB when browserifying it so if all you need is reading chunks, a different module might be a better fit

**Comment by janko** [comment]
Ok, that makes sense, thanks a lot for a quick answer!
